# Configuração do Banco de Dados PostgreSQL
quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/postgres
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# Habilitar Hibernate ORM reativo
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ativar a comunicação reativa
quarkus.hibernate-orm.reactive=true
quarkus.jackson.serialization.fail-on-empty-beans=false

